import Header from "@/components/Header/Header";
import Head from "next/head";
import Footer from "../footer/Footer";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function Layout({ children, title = "Aidroo" }) {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="w-full">{children}</main>
      <Footer />
    </div>
  );
}
