import Header from "@/components/Header/Header";
import Footer from "@/components/footer/Footer";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Aidroo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="w-full ">
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
