import { ThemeProvider } from "@/components/theme-provider";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"], // You can specify the font weights you need
});

export const metadata = {
  title: "Aidroo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light">
      <body className={roboto.className}>
        <ThemeProvider
          attribute="class"
          enableSystem
          themes={["light", "dark"]}
          disableTransitionOnChange
        >
          <main className="w-full ">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
